"""ML inference module — called by FastAPI backend."""

import json
import pickle
import warnings
import numpy as np
import pandas as pd
from pathlib import Path

warnings.filterwarnings('ignore')

MODEL_DIR = Path(__file__).parent / "models"

# Ordinal maps, min/max constants and composite weights are not hardcoded here.
# They are fitted in data/processed/preprocess.py and written to
# models/preprocessing_params.json, so training and inference cannot drift apart.
with open(MODEL_DIR / "preprocessing_params.json") as _f:
    PARAMS = json.load(_f)

ORDINAL_MAPPINGS = PARAMS["ordinal_mappings"]
ORDINAL_MEDIANS = PARAMS["ordinal_medians"]
MINMAX = PARAMS["minmax"]
MEDIANS = PARAMS["medians"]
CLIP_BOUNDS = PARAMS["clip_bounds"]


def _clip_to_training_domain(d: dict) -> dict:
    """Clip raw numeric inputs to the IQR bounds fitted during training.

    preprocess.py clips these columns before deriving any ratio, so an
    unclipped live value would produce a ratio the model never saw.
    """
    out = dict(d)
    for col, b in CLIP_BOUNDS.items():
        if out.get(col) is not None:
            out[col] = float(min(max(float(out[col]), b["lo"]), b["hi"]))
    return out

# Nominal columns and their expected one-hot categories
NOMINAL_CATEGORIES = {
    'gender': ['Female', 'Male', 'Other'],
    'occupation': ['Business', 'Freelancer', 'Retired', 'Salaried', 'Self-Employed', 'Student'],
    'marital_status': ['Divorced', 'Married', 'Single', 'Widowed'],
    'location': ['Rural', 'Semi-Urban', 'Urban'],
    'employment_type': ['Contract', 'Full-Time', 'Part-Time', 'Unemployed'],
}


def _norm(value: float, key: str) -> float:
    """Min-max normalise using the training-fitted range, clamped to [0, 1].

    Training data was IQR-clipped before these ranges were computed, so a live
    value outside them is out-of-distribution and is clamped rather than
    extrapolated.
    """
    lo, hi = MINMAX[key]["min"], MINMAX[key]["max"]
    if hi - lo < 1e-12:
        return 0.0
    return float(min(max((value - lo) / (hi - lo), 0.0), 1.0))


def _encode_ordinal(column: str, value) -> float:
    """Map an ordinal category to its training index; unseen -> training median."""
    mapping = ORDINAL_MAPPINGS[column]
    if str(value) in mapping:
        return float(mapping[str(value)])
    return ORDINAL_MEDIANS[f"{column}_encoded"]


def _as_savings_fraction(savings_rate: float) -> float:
    """Convert savings_rate from the API's percentage scale to the model's.

    docs/api-contract.json defines savings_rate as a percentage in [0, 100].
    The model was trained on the raw dataset column, a fraction in [-0.1, 0.6].
    The conversion is unconditional: a magnitude test would misread a genuine
    input of 0.5 (meaning half a percent) as 50%.
    """
    return savings_rate / 100.0


# ─── Model loading ────────────────────────────────────────────────────────────

_cache = {}


def load_models() -> dict:
    """Load all pkl and json artifacts from MODEL_DIR, return as dict."""
    global _cache
    if _cache:
        return _cache

    with open(MODEL_DIR / "risk_model.pkl", 'rb') as f:
        risk_model = pickle.load(f)

    with open(MODEL_DIR / "investment_model.pkl", 'rb') as f:
        invest_model = pickle.load(f)

    with open(MODEL_DIR / "label_encoder_risk.pkl", 'rb') as f:
        le_risk = pickle.load(f)

    with open(MODEL_DIR / "label_encoder_investment.pkl", 'rb') as f:
        le_invest = pickle.load(f)

    with open(MODEL_DIR / "feature_columns.json") as f:
        feature_columns = json.load(f)

    with open(MODEL_DIR / "model_metadata.json") as f:
        metadata = json.load(f)

    _cache = {
        "risk_model": risk_model,
        "invest_model": invest_model,
        "le_risk": le_risk,
        "le_invest": le_invest,
        "feature_columns": feature_columns,
        "metadata": metadata,
    }
    return _cache


# ─── Feature engineering (mirrors Agent 2's preprocess.py) ───────────────────

def _compute_engineered_features(d: dict) -> dict:
    """Compute derived features exactly as data/processed/preprocess.py does.

    Any change to the formulas in preprocess.py must be mirrored here, and the
    fitted constants must be regenerated by re-running that script.
    """
    d = _clip_to_training_domain(d)

    monthly_income = float(d.get('monthly_income', 1) or 1)
    monthly_expenses = float(d.get('monthly_expenses', 0) or 0)
    total_debt = float(d.get('total_debt', 0) or 0)
    luxury_spending_pct = float(d.get('luxury_spending_pct', 0) or 0)
    age = float(d.get('age', 30) or 30)
    emergency_fund_months = float(d.get('emergency_fund_months', 0) or 0)
    credit_score = float(d.get('credit_score', 600) or 600)
    investment_experience_years = float(d.get('investment_experience_years', 0) or 0)

    savings_rate = _as_savings_fraction(float(d.get('savings_rate', 0) or 0))

    if monthly_income > 0:
        debt_to_income_ratio = total_debt / (monthly_income * 12)
        savings_ratio = (monthly_income - monthly_expenses) / monthly_income
        expense_ratio = monthly_expenses / monthly_income
        luxury_to_income_ratio = (luxury_spending_pct / 100.0) * monthly_expenses / monthly_income
        age_income_ratio = monthly_income / age if age > 0 else MEDIANS['age_income_ratio']
    else:
        debt_to_income_ratio = MEDIANS['debt_to_income_ratio']
        savings_ratio = MEDIANS['savings_ratio']
        expense_ratio = MEDIANS['expense_ratio']
        luxury_to_income_ratio = MEDIANS['luxury_to_income_ratio']
        age_income_ratio = MEDIANS['age_income_ratio']

    inv_freq_enc = _encode_ordinal('investment_frequency', d.get('investment_frequency'))
    ins_cov_enc = _encode_ordinal('insurance_coverage', d.get('insurance_coverage'))

    # behavioral_composite_score: weights 0.35 / 0.25 / 0.20 / 0.20, scaled to 0-100
    behavioral_composite_score = 100.0 * (
        0.35 * _norm(investment_experience_years, 'investment_experience_years')
        + 0.25 * _norm(inv_freq_enc, 'investment_frequency_encoded')
        + 0.20 * _norm(ins_cov_enc, 'insurance_coverage_encoded')
        + 0.20 * _norm(emergency_fund_months, 'emergency_fund_months')
    )

    # financial_discipline_score: weights 0.40 / 0.35 / 0.25, scaled to 0-100.
    # The debt term is inverted so that lower debt yields a higher score.
    financial_discipline_score = 100.0 * (
        0.40 * _norm(savings_rate, 'savings_rate')
        + 0.35 * _norm(credit_score, 'credit_score')
        + 0.25 * (1.0 - _norm(debt_to_income_ratio, 'debt_to_income_ratio'))
    )

    out = dict(d)
    out.update({
        'savings_rate': savings_rate,  # model was trained on the fraction
        'debt_to_income_ratio': debt_to_income_ratio,
        'savings_ratio': savings_ratio,
        'expense_ratio': expense_ratio,
        'luxury_to_income_ratio': luxury_to_income_ratio,
        'age_income_ratio': age_income_ratio,
        'behavioral_composite_score': behavioral_composite_score,
        'financial_discipline_score': financial_discipline_score,
    })
    return out


def preprocess_input(user_input: dict) -> pd.DataFrame:
    """
    Accept raw user input dict matching the assessment form fields.
    Apply the same feature engineering as Agent 2's preprocess.py:
      - debt_to_income_ratio, savings_ratio, expense_ratio,
        behavioral_composite_score, financial_discipline_score,
        luxury_to_income_ratio, age_income_ratio
      - encode ordinal columns
      - one-hot encode nominal columns
      - align columns to feature_columns.json (fill missing with 0)
    Returns DataFrame ready for prediction.
    """
    models_dict = load_models()
    feature_columns = models_dict['feature_columns']

    # 1. Compute engineered features
    d = _compute_engineered_features(user_input)

    # 2. Ordinal encoding — indices and unseen-value fallbacks come from training
    for col in ORDINAL_MAPPINGS:
        d[f'{col}_encoded'] = _encode_ordinal(col, d.get(col))

    # 3. One-hot encode nominal columns
    for col, categories in NOMINAL_CATEGORIES.items():
        val = str(d.get(col, ''))
        for cat in categories:
            ohe_key = f"{col}_{cat}"
            d[ohe_key] = 1 if val == cat else 0

    # 4. Build a single-row DataFrame
    row = {}
    for col in feature_columns:
        row[col] = d.get(col, 0)

    df_out = pd.DataFrame([row], columns=feature_columns)
    df_out = df_out.fillna(0)
    return df_out


# ─── Financial Decision Score ─────────────────────────────────────────────────

def _compute_financial_decision_score(d: dict) -> float:
    """Financial decision score (0-100).

    Reproduces the definition used to build the dataset in
    data/raw/generate_dataset.py, with the Gaussian noise term omitted so a
    given input always yields the same score.
    """
    savings_rate = _as_savings_fraction(float(d.get('savings_rate', 0) or 0))
    credit_score = float(d.get('credit_score', 600) or 600)
    emergency_fund_months = float(d.get('emergency_fund_months', 0) or 0)
    investment_experience_years = float(d.get('investment_experience_years', 0) or 0)
    total_debt = float(d.get('total_debt', 0) or 0)
    monthly_income = float(d.get('monthly_income', 1) or 1)

    debt_to_income = total_debt / (monthly_income * 12 + 1)

    score = (
        min(max(savings_rate, 0.0), 1.0) * 30
        + (credit_score - 300) / 600 * 25
        + (1 - min(debt_to_income, 5.0) / 5) * 20
        + min(investment_experience_years, 20) / 20 * 15
        + min(emergency_fund_months, 24) / 24 * 10
    )
    return round(max(0.0, min(100.0, score)), 2)


# ─── SHAP values for inference ───────────────────────────────────────────────

def _get_shap_values(model, X_df: pd.DataFrame, model_name: str) -> dict:
    """
    Compute SHAP values for a single input row.
    Returns top-10 features by absolute SHAP value.
    Falls back to model feature_importances_ for tree models when SHAP fails.
    """
    try:
        import shap
        tree_models = ('Random Forest', 'XGBoost', 'LightGBM', 'CatBoost')
        if model_name in tree_models:
            explainer = shap.TreeExplainer(model)
            sv = explainer.shap_values(X_df)
        else:
            # For MLP: use a very small background (just the input itself as background)
            explainer = shap.KernelExplainer(model.predict_proba, X_df)
            sv = explainer.shap_values(X_df)

        feature_cols = X_df.columns.tolist()

        # Handle 3D (n_samples, n_features, n_classes) or list of 2D arrays
        if isinstance(sv, np.ndarray):
            if sv.ndim == 3:
                # (n_samples, n_features, n_classes) -> mean over classes, take row 0
                sv_row = np.abs(sv[0]).mean(axis=1)   # (n_features,)
            elif sv.ndim == 2:
                sv_row = np.abs(sv[0])
            else:
                sv_row = np.abs(sv)
        elif isinstance(sv, list):
            # list of (n_samples, n_features): mean abs across classes, row 0
            sv_row = np.mean([np.abs(s[0]) for s in sv], axis=0)
        else:
            sv_row = np.abs(np.array(sv).ravel())

        shap_dict = dict(zip(feature_cols, sv_row.tolist()))
        top10 = dict(sorted(shap_dict.items(), key=lambda x: abs(x[1]), reverse=True)[:10])
        return {k: round(v, 6) for k, v in top10.items()}
    except Exception:
        # Fallback: use model feature_importances_ for tree models
        try:
            if hasattr(model, 'feature_importances_'):
                fi = model.feature_importances_
                feature_cols = X_df.columns.tolist()
                shap_dict = dict(zip(feature_cols, fi.tolist()))
                top10 = dict(sorted(shap_dict.items(), key=lambda x: abs(x[1]), reverse=True)[:10])
                return {k: round(v, 6) for k, v in top10.items()}
        except Exception:
            pass
        return {}


# ─── Behavioral bias detection ───────────────────────────────────────────────

def _detect_biases(user_input: dict, risk_category: str, investment_preference: str,
                   behavioral_composite_score: float) -> list:
    """Detect behavioral biases from input and prediction results."""
    biases = []

    savings_rate = float(user_input.get('savings_rate', 0) or 0)
    subscription_count = int(user_input.get('subscription_count', 0) or 0)
    credit_score = float(user_input.get('credit_score', 600) or 600)
    investment_experience_years = float(user_input.get('investment_experience_years', 0) or 0)
    investment_frequency = str(user_input.get('investment_frequency', 'Never'))
    online_spending_pct = float(user_input.get('online_spending_pct', 0) or 0)
    luxury_spending_pct = float(user_input.get('luxury_spending_pct', 0) or 0)
    emergency_fund_months = float(user_input.get('emergency_fund_months', 0) or 0)
    total_debt = float(user_input.get('total_debt', 0) or 0)
    monthly_income = float(user_input.get('monthly_income', 1) or 1)
    age = int(user_input.get('age', 30) or 30)

    # Loss Aversion: Low risk category but significant investment experience
    if risk_category == 'Low' and investment_experience_years > 5:
        biases.append("Loss Aversion — Despite significant investment experience (>5 years), you prefer low-risk instruments, suggesting fear of losses outweighs potential gains.")

    # Overconfidence: Invests frequently but has a poor credit score
    if investment_frequency == 'Weekly' and credit_score < 600:
        biases.append("Overconfidence Bias — Frequent weekly investing despite a low credit score (<600) may indicate overestimation of financial capabilities.")

    # Present Bias: Low savings but many subscriptions
    if savings_rate < 10 and subscription_count > 5:
        biases.append("Present Bias — Low savings rate (<10%) combined with many active subscriptions (>5) indicates prioritizing present consumption over future financial security.")

    # Herd Mentality: Crypto preference with low behavioral score
    if investment_preference == 'Crypto' and behavioral_composite_score < 40:
        biases.append("Herd Mentality — Preference for Crypto with low financial behavioral score (<40) may suggest following market trends rather than sound investment principles.")

    # Status Quo Bias: Never invests but has significant income
    if investment_frequency == 'Never' and monthly_income > 50000:
        biases.append("Status Quo Bias — High income but no investment activity suggests reluctance to change current financial behavior.")

    # Anchoring Bias: High luxury spending with high debt
    dti = total_debt / monthly_income if monthly_income > 0 else 0
    if luxury_spending_pct > 30 and dti > 2:
        biases.append("Anchoring Bias — Maintaining high luxury spending (>30%) despite high debt-to-income ratio (>2x) suggests anchoring to a past lifestyle that is no longer financially sustainable.")

    # Recency Bias: High online spending
    if online_spending_pct > 50:
        biases.append("Recency Bias — Unusually high online spending (>50%) may indicate susceptibility to impulse purchases and recent digital marketing trends.")

    # Neglect of Probability: No emergency fund but high investment activity
    if emergency_fund_months < 1 and investment_frequency in ('Weekly', 'Monthly'):
        biases.append("Neglect of Probability — Active investing without an emergency fund (<1 month) ignores the probability of financial shocks that could force liquidation of investments.")

    # Mental Accounting: Young with high savings but no investments
    if age < 30 and savings_rate > 30 and investment_frequency == 'Never':
        biases.append("Mental Accounting — Keeping large savings (>30%) in cash/savings accounts instead of investing may reflect siloed thinking about money rather than optimizing overall wealth.")

    return biases


# ─── Recommendations ─────────────────────────────────────────────────────────

def _generate_recommendations(user_input: dict, risk_category: str,
                               investment_preference: str,
                               behavioral_composite_score: float,
                               financial_discipline_score: float) -> list:
    """Generate 3-5 personalized financial recommendations."""
    recs = []

    savings_rate = float(user_input.get('savings_rate', 0) or 0)
    credit_score = float(user_input.get('credit_score', 600) or 600)
    emergency_fund_months = float(user_input.get('emergency_fund_months', 0) or 0)
    total_debt = float(user_input.get('total_debt', 0) or 0)
    monthly_income = float(user_input.get('monthly_income', 1) or 1)
    investment_experience_years = float(user_input.get('investment_experience_years', 0) or 0)
    subscription_count = int(user_input.get('subscription_count', 0) or 0)
    insurance_coverage = str(user_input.get('insurance_coverage', 'None'))
    investment_frequency = str(user_input.get('investment_frequency', 'Never'))
    dti = total_debt / monthly_income if monthly_income > 0 else 0

    # Emergency fund
    if emergency_fund_months < 3:
        recs.append(f"Build an emergency fund: Aim for at least 3-6 months of expenses ({3 - int(emergency_fund_months)} more months needed). Start with automatic transfers of 5-10% of monthly income to a high-yield savings account.")

    # Savings rate
    if savings_rate < 20:
        recs.append(f"Increase savings rate: Your current savings rate of {savings_rate:.0f}% is below the recommended 20%. Use the 50/30/20 rule — 50% needs, 30% wants, 20% savings — to build long-term wealth.")

    # Debt management
    if dti > 1.5:
        recs.append(f"Prioritize debt reduction: Your debt-to-income ratio of {dti:.1f}x is high. Focus on the avalanche method — pay off highest-interest debt first while maintaining minimum payments on others.")

    # Credit improvement
    if credit_score < 700:
        recs.append(f"Improve credit score: Your score of {int(credit_score)} limits financial options. Pay bills on time, keep credit utilization below 30%, and avoid opening new credit lines unnecessarily.")

    # Risk-based investment advice
    if risk_category == 'Low':
        if investment_experience_years > 2:
            recs.append("Diversify beyond safe instruments: Given your experience, consider allocating 10-20% of your portfolio to balanced mutual funds or index ETFs for inflation-beating returns while keeping your core in FDs or Government bonds.")
        else:
            recs.append("Start with low-risk investments: Begin with PPF, NSC, or debt mutual funds. These offer better returns than savings accounts with capital protection, suitable for your conservative profile.")
    elif risk_category == 'Medium':
        recs.append("Balanced portfolio strategy: Allocate 50-60% to equity (large-cap mutual funds/index funds), 30-40% to debt instruments, and 10% to gold for optimal risk-adjusted returns matching your Medium risk profile.")
    else:  # High
        recs.append("Aggressive growth strategy: With your High risk appetite, consider 70-80% equity exposure through diversified funds, including mid/small-cap allocation. Ensure you have at least 3 months emergency fund before deploying capital in volatile assets.")

    # Subscription audit
    if subscription_count > 5:
        recs.append(f"Audit recurring subscriptions: You have {subscription_count} active subscriptions. Review each for usage and cancel unused ones — this can free up INR {subscription_count * 300:,}-{subscription_count * 1000:,}/month for productive investment.")

    # Insurance
    if insurance_coverage in ('None', 'Basic'):
        recs.append("Upgrade insurance coverage: Comprehensive life and health insurance is the foundation of financial security. Inadequate coverage is your biggest financial risk — get a term plan for 10-15x annual income and adequate health cover.")

    # Investment frequency
    if investment_frequency == 'Never' and monthly_income > 20000:
        recs.append("Start a SIP immediately: Set up a Systematic Investment Plan (SIP) with as little as INR 500/month in an index fund. Time in market beats timing the market — starting today is better than waiting for the 'right time'.")

    return recs[:5]  # Return max 5 recommendations


# ─── Main inference function ──────────────────────────────────────────────────

def predict(user_input: dict) -> dict:
    """
    Main inference function.

    Returns:
    {
      "risk_category": str,                   # "Low"/"Medium"/"High"
      "risk_confidence": float,               # probability of predicted class
      "risk_probabilities": dict,             # {"Low": p, "Medium": p, "High": p}
      "investment_preference": str,
      "investment_confidence": float,
      "financial_decision_score": float,      # computed from features
      "behavioral_composite_score": float,
      "financial_discipline_score": float,
      "shap_values": dict,                    # top 10 feature -> shap_value
      "feature_importance": dict,             # top 10 feature -> importance
      "recommendations": list[str],           # 3-5 personalized recommendations
      "behavioral_biases": list[str]          # detected behavioral biases
    }
    """
    artifacts = load_models()
    risk_model = artifacts['risk_model']
    invest_model = artifacts['invest_model']
    le_risk = artifacts['le_risk']
    le_invest = artifacts['le_invest']
    metadata = artifacts['metadata']

    # Preprocess
    X_df = preprocess_input(user_input)

    # ── Risk prediction ──
    risk_proba = risk_model.predict_proba(X_df)[0]
    risk_pred_idx = int(np.argmax(risk_proba))
    # le_risk.classes_ = ['Low', 'Medium', 'High']
    risk_category = le_risk.classes_[risk_pred_idx]
    risk_confidence = float(risk_proba[risk_pred_idx])
    risk_probabilities = {
        str(cls): round(float(p), 4)
        for cls, p in zip(le_risk.classes_, risk_proba)
    }

    # ── Investment preference prediction ──
    invest_proba = invest_model.predict_proba(X_df)[0]
    invest_pred_idx = int(np.argmax(invest_proba))
    investment_preference = str(le_invest.classes_[invest_pred_idx])
    investment_confidence = float(invest_proba[invest_pred_idx])

    # ── Derived scores ──
    engineered = _compute_engineered_features(user_input)
    financial_decision_score = _compute_financial_decision_score(user_input)
    behavioral_composite_score = float(engineered.get('behavioral_composite_score', 0.0))
    financial_discipline_score = float(engineered.get('financial_discipline_score', 0.0))

    # ── SHAP values ──
    model_name = metadata.get('best_model_name', 'Random Forest')
    shap_vals = _get_shap_values(risk_model, X_df, model_name)

    # ── Feature importance from metadata ──
    feature_importance = metadata.get('feature_importance_top10', {})

    # ── Behavioral biases ──
    behavioral_biases = _detect_biases(
        user_input, risk_category, investment_preference, behavioral_composite_score
    )

    # ── Recommendations ──
    recommendations = _generate_recommendations(
        user_input, risk_category, investment_preference,
        behavioral_composite_score, financial_discipline_score
    )

    return {
        "risk_category": str(risk_category),
        "risk_confidence": round(risk_confidence, 4),
        "risk_probabilities": risk_probabilities,
        "investment_preference": investment_preference,
        "investment_confidence": round(investment_confidence, 4),
        "financial_decision_score": financial_decision_score,
        "behavioral_composite_score": round(behavioral_composite_score, 2),
        "financial_discipline_score": round(financial_discipline_score, 2),
        "shap_values": shap_vals,
        "feature_importance": {k: round(float(v), 6) for k, v in feature_importance.items()},
        "recommendations": recommendations,
        "behavioral_biases": behavioral_biases,
    }
