// ============================================================
// SOURCE OF TRUTH: docs/api-contract.json
// Do NOT edit this file without first updating api-contract.json
// ============================================================

// ---- Request -----------------------------------------------

export interface AssessmentInput {
  // Demographics
  age: number
  gender: 'Male' | 'Female' | 'Other'
  education: 'High School' | 'Graduate' | 'Post Graduate' | 'PhD'
  occupation: 'Salaried' | 'Self-Employed' | 'Business' | 'Freelancer' | 'Student' | 'Retired'
  income_level: 'Low' | 'Middle' | 'High'
  marital_status: 'Single' | 'Married' | 'Divorced' | 'Widowed'
  dependents: number
  location: 'Urban' | 'Semi-Urban' | 'Rural'
  employment_type: 'Full-Time' | 'Part-Time' | 'Contract' | 'Unemployed'
  years_of_experience: number
  // Financial
  monthly_income: number
  monthly_expenses: number
  savings_rate: number
  emergency_fund_months: number
  total_debt: number
  loan_amount: number
  credit_score: number
  investment_experience_years: number
  investment_frequency: 'Never' | 'Rarely' | 'Monthly' | 'Weekly'
  insurance_coverage: 'None' | 'Basic' | 'Comprehensive'
  // Lifestyle
  shopping_frequency: 'Rarely' | 'Monthly' | 'Weekly' | 'Daily'
  online_spending_pct: number
  luxury_spending_pct: number
  subscription_count: number
  gaming_expenses_monthly: number
  travel_expenses_annual: number
}

// ---- Shared prediction payload (inside data: {}) -----------

export interface PredictionResult {
  risk_category: 'Low' | 'Medium' | 'High'
  risk_confidence: number                          // 0–1
  risk_probabilities: Record<'Low' | 'Medium' | 'High', number>
  investment_preference: 'FD' | 'Mutual Funds' | 'Stocks' | 'Gold' | 'Crypto'
  investment_confidence: number                    // 0–1
  financial_decision_score: number                 // 0–100
  behavioral_composite_score: number               // 0–100
  financial_discipline_score: number               // 0–100
  shap_values: Record<string, number>              // top 10 features
  feature_importance: Record<string, number>       // top 10 features
  recommendations: string[]
  behavioral_biases: string[]
}

// ---- POST /predict response --------------------------------

export interface PredictionResponse {
  success: boolean
  data: PredictionResult
}

// ---- POST /assessment & GET /assessment/{id} response ------

export interface AssessmentResponse {
  success: boolean
  assessment_id: string
  data: PredictionResult
}

// ---- GET /assessments list item ----------------------------

export interface AssessmentRecord {
  id: string
  created_at: string
  status: 'pending' | 'completed' | 'failed'
  age: number | null
  gender: string | null
  income_level: string | null
  prediction: PredictionResult | null
}

export interface AssessmentsListResponse {
  success: boolean
  total: number
  items: AssessmentRecord[]
}

// ---- GET /analytics ----------------------------------------

export interface AnalyticsResponse {
  total_assessments: number
  risk_distribution: Record<string, number>
  investment_distribution: Record<string, number>
  avg_financial_decision_score: number
  avg_behavioral_composite_score: number
  avg_financial_discipline_score: number
  assessments_by_date: Array<{ date: string; count: number }>
}

// ---- GET /health -------------------------------------------

export interface HealthResponse {
  status: string
  model_loaded: boolean
  database: string
  version: string
}

// ---- GET /model/info ---------------------------------------

export interface ModelInfoResponse {
  best_model_name: string
  accuracy: number
  precision: number
  recall: number
  f1_score: number
  roc_auc: number
  cv_f1_mean: number
  cv_f1_std: number
  training_date: string
  n_features: number
  n_samples: number
  class_names: string[]
  feature_importance_top10: Record<string, number>
}
